
export const ADD_CATEGORY_REQUEST="ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS="ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL="ADD_CATEGORY_FAIL";

export const GET_CATEGORY_REQUEST="GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL="GET_CATEGORY_FAIL";

export const UPDATE_CATEGORY_REQUEST="UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL="UPDATE_CATEGORY_FAIL";

export const DELETE_SUB_CATEGORY_REQUEST="DELETE_SUB_CATEGORY_REQUEST";
export const DELETE_SUB_CATEGORY_SUCCESS="DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAIL="DELETE_SUB_CATEGORY_FAIL";

export const ADD_SUB_CATEGORY_REQUEST="ADD_SUB_CATEGORY_REQUEST";
export const ADD_SUB_CATEGORY_SUCCESS="ADD_SUB_CATEGORY_SUCCESS";
export const ADD_SUB_CATEGORY_FAIL="ADD_SUB_CATEGORY_FAIL";

export const GET_SUB_CATEGORY_REQUEST="GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_SUCCESS="GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_FAIL="GET_SUB_CATEGORY_FAIL";

export const UPDATE_SUB_CATEGORY_REQUEST="UPDATE_SUB_CATEGORY_REQUEST";
export const UPDATE_SUB_CATEGORY_SUCCESS="UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_FAIL="UPDATE_SUB_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST="DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL="DELETE_CATEGORY_FAIL";

export const AUTH_LOGIN_REQUEST="AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS="AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL="AUTH_LOGIN_FAIL";

export const AUTH_FORGOT_PASSWORD_REQUEST="AUTH_FORGOT_PASSWORD_REQUEST";
export const AUTH_FORGOT_PASSWORD_SUCCESS="AUTH_FORGOT_PASSWORD_SUCCESS";
export const AUTH_FORGOT_PASSWORD_FAIL="AUTH_FORGOT_PASSWORD_FAIL";

export const ADD_POST_REQUEST="ADD_POST_REQUEST";
export const ADD_POST_SUCCESS="ADD_POST_SUCCESS";
export const ADD_POST_FAIL="ADD_POST_FAIL";


export const GET_POST_REQUEST="GET_POST_REQUEST";
export const GET_POST_SUCCESS="GET_POST_SUCCESS";
export const GET_POST_FAIL="GET_POST_FAIL";

export const ADD_COUNTRY_REQUEST="ADD_COUNTRY_REQUEST";
export const ADD_COUNTRY_SUCCESS="ADD_COUNTRY_SUCCESS";
export const ADD_COUNTRY_FAIL="ADD_COUNTRY_FAIL";

export const GET_COUNTRY_REQUEST="GET_COUNTRY_REQUEST";
export const GET_COUNTRY_SUCCESS="GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_FAIL="GET_COUNTRY_FAIL";

export const UPDATE_COUNTRY_REQUEST="UPDATE_COUNTRY_REQUEST";
export const UPDATE_COUNTRY_SUCCESS="UPDATE_COUNTRY_SUCCESS";
export const UPDATE_COUNTRY_FAIL="UPDATE_COUNTRY_FAIL";

export const DELETE_COUNTRY_REQUEST="DELETE_COUNTRY_REQUEST";
export const DELETE_COUNTRY_SUCCESS="DELETE_COUNTRY_SUCCESS";
export const DELETE_COUNTRY_FAIL="DELETE_COUNTRY_FAIL";


export const ADD_STATE_REQUEST="ADD_STATE_REQUEST";
export const ADD_STATE_SUCCESS="ADD_STATE_SUCCESS";
export const ADD_STATE_FAIL="ADD_STATE_FAIL";

export const GET_STATE_REQUEST="GET_STATE_REQUEST";
export const GET_STATE_SUCCESS="GET_STATE_SUCCESS";
export const GET_STATE_FAIL="GET_STATE_FAIL";

export const UPDATE_STATE_REQUEST="UPDATE_STATE_REQUEST";
export const UPDATE_STATE_SUCCESS="UPDATE_STATE_SUCCESS";
export const UPDATE_STATE_FAIL="UPDATE_STATE_FAIL";

export const DELETE_STATE_REQUEST="DELETE_STATE_REQUEST";
export const DELETE_STATE_SUCCESS="DELETE_STATE_SUCCESS";
export const DELETE_STATE_FAIL="DELETE_STATE_FAIL";


export const ADD_CITY_REQUEST="ADD_CITY_REQUEST";
export const ADD_CITY_SUCCESS="ADD_CITY_SUCCESS";
export const ADD_CITY_FAIL="ADD_CITY_FAIL";

export const GET_CITY_REQUEST="GET_CITY_REQUEST";
export const GET_CITY_SUCCESS="GET_CITY_SUCCESS";
export const GET_CITY_FAIL="GET_CITY_FAIL";

export const UPDATE_CITY_REQUEST="UPDATE_CITY_REQUEST";
export const UPDATE_CITY_SUCCESS="UPDATE_CITY_SUCCESS";
export const UPDATE_CITY_FAIL="UPDATE_CITY_FAIL";

export const DELETE_CITY_REQUEST="DELETE_CITY_REQUEST";
export const DELETE_CITY_SUCCESS="DELETE_CITY_SUCCESS";
export const DELETE_CITY_FAIL="DELETE_CITY_FAIL";

export const AUTH_PROFILE_REQUEST="AUTH_PROFILE_REQUEST";
export const AUTH_PROFILE_SUCCESS="AUTH_PROFILE_SUCCESS";
export const AUTH_PROFILE_FAIL="AUTH_PROFILE_FAIL";

export const GET_USERS_REQUEST="GET_USERS_REQUEST";
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS";
export const GET_USERS_FAIL="GET_USERS_FAIL";

export const DELETE_POST_REQUEST="DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL="DELETE_POST_FAIL";


export const UPDATE_POST_REQUEST="UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS="UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL="UPDATE_POST_FAIL";