
export const ADD_CATEGORY_REQUEST="ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS="ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL="ADD_CATEGORY_FAIL";

export const GET_CATEGORY_REQUEST="GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL="GET_CATEGORY_FAIL";

export const UPDATE_CATEGORY_REQUEST="UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL="UPDATE_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST="DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL="DELETE_CATEGORY_FAIL";

export const ADD_SUB_CATEGORY_REQUEST="ADD_SUB_CATEGORY_REQUEST";
export const ADD_SUB_CATEGORY_SUCCESS="ADD_SUB_CATEGORY_SUCCESS";
export const ADD_SUB_CATEGORY_FAIL="ADD_SUB_CATEGORY_FAIL";

export const GET_SUB_CATEGORY_REQUEST="GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_SUCCESS="GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_FAIL="GET_SUB_CATEGORY_FAIL";

export const UPDATE_SUB_CATEGORY_REQUEST="UPDATE_SUB_CATEGORY_REQUEST";
export const UPDATE_SUB_CATEGORY_SUCCESS="UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_FAIL="UPDATE_SUB_CATEGORY_FAIL";

export const AUTH_LOGIN_REQUEST="AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS="AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL="AUTH_LOGIN_FAIL";

export const AUTH_FORGOT_PASSWORD_REQUEST="AUTH_FORGOT_PASSWORD_REQUEST";
export const AUTH_FORGOT_PASSWORD_SUCCESS="AUTH_FORGOT_PASSWORD_SUCCESS";
export const AUTH_FORGOT_PASSWORD_FAIL="AUTH_FORGOT_PASSWORD_FAIL";

export const ADD_POST_REQUEST="ADD_POST_REQUEST";
export const ADD_POST_SUCCESS="ADD_POST_SUCCESS";
export const ADD_POST_FAIL="ADD_POST_FAIL";


export const GET_POST_REQUEST="GET_POST_REQUEST";
export const GET_POST_SUCCESS="GET_POST_SUCCESS";
export const GET_POST_FAIL="GET_POST_FAIL";
